# Generated by Django 2.0.4 on 2018-04-10 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('idalmacen', models.AutoField(primary_key=True, serialize=False)),
                ('almacen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionEvento',
            fields=[
                ('idClasificacion_evento', models.AutoField(primary_key=True, serialize=False)),
                ('Clasificacion_evento', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_cliente', models.CharField(max_length=45)),
                ('Apellido_cliente', models.CharField(max_length=45)),
                ('Telefono_cliente', models.CharField(max_length=45)),
                ('Correo_electronico', models.CharField(max_length=45)),
                ('Otros_datos_cliente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvento',
            fields=[
                ('idDetalle_evento', models.AutoField(primary_key=True, serialize=False)),
                ('FechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('FechaFin', models.DateField()),
                ('ClasificacionEvento_idClasificacionEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.ClasificacionEvento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEvento', models.CharField(max_length=45)),
                ('CodigoEvento', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCliente',
            fields=[
                ('idEventoCliente', models.AutoField(primary_key=True, serialize=False)),
                ('ClienteIdCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Cliente')),
                ('EventoIdEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoMaterial',
            fields=[
                ('idEventoMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('EventoIdEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet_Type',
            fields=[
                ('idpallet_type', models.AutoField(primary_key=True, serialize=False)),
                ('pallet_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.IntegerField()),
                ('description', models.TextField()),
                ('ple', models.IntegerField()),
                ('cajas', models.IntegerField()),
                ('unidades', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('fecha_em', models.DateField(auto_now_add=True)),
                ('bar_code', models.BigIntegerField()),
                ('cant_ideal', models.BigIntegerField()),
                ('almacen_idalmacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Almacen')),
                ('pallet_type_idpallet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Pallet_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('idubication', models.AutoField(primary_key=True, serialize=False)),
                ('ubication', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('idunity', models.AutoField(primary_key=True, serialize=False)),
                ('unity', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ubication_idubication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Ubication'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidad_idunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Unity'),
        ),
        migrations.AddField(
            model_name='eventomaterial',
            name='MaterialIdMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Product'),
        ),
        migrations.AddField(
            model_name='detalleevento',
            name='Evento_idEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_inventory.Evento'),
        ),
    ]
